#!/usr/bin/env node
// validate-cv.mjs — build gate for content/cv.json.
// Hard errors (exit 1): missing name/email, malformed entries, placeholder
// text (TODO, lorem, "Your ...", "[ ]"), links that are not https URLs.
// Warnings: sections still empty — printed so the build log says what the
// site is not yet showing.
import { readFileSync, existsSync } from 'node:fs';

const cv = JSON.parse(readFileSync(new URL('../content/cv.json', import.meta.url), 'utf8'));
const { works } = JSON.parse(readFileSync(new URL('../content/works.json', import.meta.url), 'utf8'));
const errors = [];
const warnings = [];

const PLACEHOLDER = /\b(TODO|TBD|lorem|ipsum|placeholder|your (name|title|role|company))\b|\[[^\]]*\]/i;
const walk = (v, path) => {
  if (typeof v === 'string') { if (PLACEHOLDER.test(v)) errors.push(`${path}: placeholder text "${v.slice(0, 60)}"`); }
  else if (Array.isArray(v)) v.forEach((x, i) => walk(x, `${path}[${i}]`));
  else if (v && typeof v === 'object') for (const [k, x] of Object.entries(v)) if (k !== '$comment') walk(x, `${path}.${k}`);
};
walk(cv, 'cv');
walk(works, 'works');

if (!cv.name?.trim()) errors.push('cv.name is required');
if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(cv.email ?? '')) errors.push('cv.email must be an email address');

for (const [i, l] of (cv.links ?? []).entries()) {
  if (!l.label?.trim()) errors.push(`links[${i}].label missing`);
  if (!/^https:\/\//.test(l.url ?? '')) errors.push(`links[${i}].url must start with https://`);
}
for (const [i, e] of (cv.experience ?? []).entries()) {
  for (const k of ['role', 'organization', 'start']) if (!e[k]?.trim()) errors.push(`experience[${i}].${k} missing`);
}
for (const [i, e] of (cv.education ?? []).entries()) {
  if (!e.institution?.trim()) errors.push(`education[${i}].institution missing`);
}
for (const [i, g] of (cv.skills ?? []).entries()) {
  if (!g.group?.trim() || !Array.isArray(g.items) || g.items.length === 0) errors.push(`skills[${i}] needs group + items`);
}
for (const [i, w] of (cv.works ?? []).entries()) {
  if (!w.title?.trim()) errors.push(`works[${i}].title missing`);
  if (w.url && !/^https:\/\//.test(w.url)) errors.push(`works[${i}].url must start with https://`);
}
if (cv.pdf && !/^\/cv\/[\w.-]+\.pdf$/.test(cv.pdf)) errors.push('cv.pdf must be /cv/<name>.pdf (generated by build-cv-pdf.mjs)');
if (cv.portrait && !existsSync(new URL(`../public${cv.portrait}`, import.meta.url))) errors.push(`cv.portrait ${cv.portrait} is not under public/`);
const slugs = new Set();
for (const [i, w] of works.entries()) {
  if (!/^[a-z0-9-]+$/.test(w.slug ?? '')) errors.push(`works[${i}].slug must be lowercase-hyphen`);
  if (slugs.has(w.slug)) errors.push(`works[${i}].slug duplicate: ${w.slug}`); slugs.add(w.slug);
  if (!w.title?.trim()) errors.push(`works[${i}].title missing`);
  if (!/^\/works\/[\w.-]+\.pdf$/.test(w.pdf ?? '')) errors.push(`works[${i}].pdf must be /works/<file>.pdf`);
  else if (!existsSync(new URL(`../public${w.pdf}`, import.meta.url))) errors.push(`works[${i}].pdf ${w.pdf} is missing under public/`);
  if (w.source && !/^https:\/\//.test(w.source)) errors.push(`works[${i}].source must start with https://`);
}

for (const k of ['headline', 'location', 'summary']) if (!cv[k]?.trim()) warnings.push(`${k} is empty (not rendered)`);
for (const k of ['experience', 'education', 'skills', 'works']) if (!(cv[k]?.length)) warnings.push(`${k} is empty (section not rendered)`);
if (!cv.pdf) warnings.push('pdf is empty (no CV viewer or download rendered)');
if (!cv.portrait) warnings.push('portrait is empty (monogram placeholder rendered)');
if (!works.length) warnings.push('works.json is empty (Work section not rendered)');

for (const w of warnings) console.warn(`validate-cv: warning: ${w}`);
if (errors.length) { for (const e of errors) console.error(`validate-cv: error: ${e}`); process.exit(1); }
console.log(`validate-cv: ok (${warnings.length} warning${warnings.length === 1 ? '' : 's'})`);
